<<<<<<< HEAD
version = '2'
=======
[run]
timeout = "10m"

[issues]
exclude-use-default = false
new = true
new-from-rev = "master"

# BUG(colin): https://github.com/kunwardeep/paralleltest/issues/8
[[issues.exclude-rules]]
linters = [ "paralleltest" ]
text = "does not use range value in test Run"

[[issues.exclude-rules]]
path = "_test\\.go"
linters = [ "funlen", "cyclop" ]

[[issues.exclude-rules]]
path = "test"
linters = [ "funlen", "cyclop" ]
>>>>>>> 626a758133e7e28499b527b7d7a27565481e96be

[linters]
default = 'none'
enable = [
<<<<<<< HEAD
  'asciicheck',
  'bodyclose',
  'cyclop',
  'dogsled',
  'durationcheck',
  'errcheck',
  'exhaustive',
  'forcetypeassert',
  'funlen',
  'gocognit',
  'goconst',
  'gocritic',
  'godot',
  'gomoddirectives',
  'goprintffuncname',
  'gosec',
  'govet',
  'ineffassign',
  'makezero',
  'misspell',
  'nakedret',
  'nestif',
  'nilerr',
  'noctx',
  'nolintlint',
  'paralleltest',
  'prealloc',
  'predeclared',
  'revive',
  'rowserrcheck',
  'sqlclosecheck',
  'staticcheck',
  'thelper',
  'unconvert',
  'unparam',
  'unused',
  'wastedassign',
  'whitespace'
=======
  "asciicheck",
  "bodyclose",
  "copyloopvar",
  "cyclop",
  "decorder",
  "dogsled",
  # "dupl", // disabled because it cannot be nolint-ed
  "durationcheck",
  "errcheck",
  "exhaustive",
  "exportloopref",
  "forcetypeassert",
  "funlen",
  "gci",
  "gocognit",
  "goconst",
  "gocritic",
  "godot",
  "gofmt",
  "gofumpt",
  "goimports",
  "gomoddirectives",
  "goprintffuncname",
  "gosimple",
  "gosec",
  "govet",
  "ineffassign",
  "makezero",
  "misspell",
  "nakedret",
  "nestif",
  "nilerr",
  "noctx",
  "nolintlint",
  "paralleltest",
  "prealloc",
  "predeclared",
  "revive",
  "rowserrcheck",
  "sqlclosecheck",
  "staticcheck",
  "stylecheck",
  "thelper",
  "unconvert",
  "unparam",
  "unused",
  "wastedassign",
  "whitespace",
>>>>>>> 626a758133e7e28499b527b7d7a27565481e96be
]

[linters.settings]
[linters.settings.exhaustive]
default-signifies-exhaustive = true

[linters.settings.misspell]
locale = 'UK'

[linters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]

[[linters.exclusions.rules]]
linters = [
  'paralleltest'
]
text = 'does not use range value in test Run'

[[linters.exclusions.rules]]
linters = [
  'cyclop',
  'funlen'
]
path = '_test\.go'

[[linters.exclusions.rules]]
linters = [
  'cyclop',
  'funlen'
]
path = 'test'

[formatters]
enable = [
  'gci',
  'gofmt',
  'gofumpt',
  'goimports'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'third_party$',
  'builtin$',
  'examples$'
]
